### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by chkalog** [applidium/Shutterbug#11]
Hello everyone!

I implemented this library a few weeks ago on my app but it seems that on some devices doesn't work perfectly, depending the size of the available storage.
I keep getting this error : 

02-10 18:17:29.245: E/dalvikvm-heap(7366): Out of memory on a 852816-byte allocation.
02-10 18:17:29.250: W/skia(7366): Use JPEG SW Decoder
02-10 18:17:29.250: W/System.err(7366): java.lang.OutOfMemoryError
02-10 18:17:29.250: W/System.err(7366):     at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
02-10 18:17:29.251: W/System.err(7366):     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:512)
02-10 18:17:29.252: W/System.err(7366):     at com.applidium.shutterbug.utils.BitmapFactoryScale.decodeSampledBitmapFromStream(BitmapFactoryScale.java:24)
02-10 18:17:29.252: W/System.err(7366):     at com.applidium.shutterbug.utils.ShutterbugManager$InputStreamHandlingTask.doInBackground(ShutterbugManager.java:171)
02-10 18:17:29.252: W/System.err(7366):     at com.applidium.shutterbug.utils.ShutterbugManager$InputStreamHandlingTask.doInBackground(ShutterbugManager.java:1)
02-10 18:17:29.253: W/System.err(7366):     at android.os.AsyncTask$2.call(AsyncTask.java:264)
02-10 18:17:29.253: W/System.err(7366):     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
02-10 18:17:29.254: W/System.err(7366):     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
02-10 18:17:29.254: W/System.err(7366):     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:208)
02-10 18:17:29.255: W/System.err(7366):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
02-10 18:17:29.256: W/System.err(7366):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
02-10 18:17:29.256: W/System.err(7366):     at java.lang.Thread.run(Thread.java:856)
02-10 18:17:29.256: W/skia(7366): onDecode(), rewind fail

This error appears in BitmapFactoryScale.java : 
-return BitmapFactory.decodeStream(generator.getStream(), null, options);

All the images I download are moreless 25KB.And this error I don't think is normal.
Could you please tell me what is going on?

**Comment by acq** [comment]
Hi
Does issue #9 solve your problem ?

**Comment by chkalog** [comment]
Hello!

Well, I have already thought about these stuff. But it seems that on my mobile phone everything works fine.But when I load my app on my tablet (with less memory) I face these exceptions.
I have also double cheked the images and their size is not bigger than 40KB.
I will try to resize the images (width and height) and I will let you know.

Thanks again for replying!

**Comment by acq** [comment]
Actually, the file size does not really matter. What matters is the dimensions of the bitmap.
For example, if you have several huge (let's say 2000x2000 pixels) png images with just one color, the file sizes will be very very small, but the decompression (creating the bitmap in memory) will require 4 millions pixels for each image, which will launch an OutOfMemoryException on many devices (for example, your tablet).

Tell me if the resize helps.

If not, you can also try to use `setImage(String url, Drawable placeholderDrawable, int desiredHeight, int desiredWidth)`
