### ISSUE TITLE
OutOfMemory error

### ISSUE THREAD

**Issue by zetxek** [applidium/Shutterbug#2]
When downloading some large images, a "OutOfMemory" error is raised. I'm not pretty sure if that can be solved without reducing the images...

12-13 12:37:10.160: E/dalvikvm(21830): Out of memory: Heap Size=63587KB, Allocated=55186KB, Limit=65536KB
12-13 12:37:10.160: E/dalvikvm(21830): Extra info: Footprint=63587KB, Allowed Footprint=63587KB, Trimmed=15032KB
12-13 12:37:10.160: D/skia(21830): --- decoder->decode returned false
12-13 12:37:10.160: W/System.err(21830): java.lang.OutOfMemoryError: (Heap Size=63587KB, Allocated=55186KB)
12-13 12:37:10.160: W/System.err(21830):    at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
12-13 12:37:10.160: W/System.err(21830):    at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:719)
12-13 12:37:10.160: W/System.err(21830):    at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:791)
12-13 12:37:10.160: W/System.err(21830):    at com.applidium.shutterbug.cache.ImageCache$BitmapDecoderTask.doInBackground(ImageCache.java:142)
12-13 12:37:10.160: W/System.err(21830):    at com.applidium.shutterbug.cache.ImageCache$BitmapDecoderTask.doInBackground(ImageCache.java:1)
12-13 12:37:10.160: W/System.err(21830):    at android.os.AsyncTask$2.call(AsyncTask.java:264)
12-13 12:37:10.160: W/System.err(21830):    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
12-13 12:37:10.160: W/System.err(21830):    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
12-13 12:37:10.160: W/System.err(21830):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:208)
12-13 12:37:10.160: W/System.err(21830):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
12-13 12:37:10.170: W/System.err(21830):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
12-13 12:37:10.170: W/System.err(21830):    at java.lang.Thread.run(Thread.java:864)
12-13 12:37:10.220: D/dalvikvm(21830): GC_FOR_ALLOC freed 45K, 14% free 55185K/63587K, paused 49ms

I attach a full trace at http://pastebin.com/KHr1hyUr

**Comment by cnordvik** [comment]
I got the same so I modified it to implement some of the suggestions here: 
http://stackoverflow.com/questions/477572/android-strange-out-of-memory-issue-while-loading-an-image-to-a-bitmap-object

The images still loads kind of slow though...

**Comment by acq** [comment]
Solved via d781d7c369b64a7bea0353b15c262efba65e758a

You can now ask for a maximum size for the image to be displayed, which will prevent an OutOfMemory error if the image is too big
